name: Build & Test & Release

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm ci

      - name: Lint files
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:14
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm ci

      - name: Run tests
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm ci

      - name: Run build
        run: npm run build

  release:
    name: Publish NPM Package
    needs: [test, lint, build]
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/next' ||
      github.ref == 'refs/heads/next-major' ||
      github.ref == 'refs/heads/alpha' ||
      github.ref == 'refs/heads/beta' ||
      contains(github.ref, '/feat/') ||
      contains(github.ref, '/hotfeat/') ||
      contains(github.ref, '/fix/')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm ci

      - name: Build files
        run: npm run build

      - name: Semantic Release
        id: release
        uses: sujimoshi/semantic-release-action@v1.4.1
        with:
          branches: |
            master
            next
            next-major
            { "name": "alpha", "prerelease": true }
            { "name": "beta", "prerelease": true }
            { "name": "*/[A-Z]+-[0-9]+/*", "prerelease": "<%= name.split('/')[1] %>", "channel": "<%= name.split('/')[1] %>" }

      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag }}
          name: ${{ steps.release.outputs.name }}
          body: ${{ steps.release.outputs.notes }}
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ !!steps.release.outputs.channel }}

      - name: Publish NPM Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SHOPMONKEY_NPM_TOKEN }}
        run: |
          npm --no-git-tag-version version ${{ steps.release.outputs.version }}
          npm publish --tag '${{ steps.release.outputs.channel }}'
